### PR TITLE
channel-permissions.md

### PR DESCRIPTION
**Pull request by EnigmaticSheep**
I read the Trello board, and talked to a few people who work on this and this was my creation.

### CODE REVIEW

**Comment by deansheather** [comment]
I think that you need to mention that channel permissions are inherited directly from server role permissions. The last two screenshots in the document don't seem to show this, as every box has a value set (not needed due to the inheritance).

For example, if I had a role called `Regulars` and I wanted to give the role read access to channel `#regulars-lounge`, I can just revoke read permissions to `@everyone`, and allow read permissions to `Regulars`.  All other permissions will be inherited,  so if you allow embeds for `@everyone` globally (server permissions) the `Regulars` role will be able to embed links in the `#regulars-lounge` channel. This inheritance only takes place if you leave the channel permission checkbox in the blank state.

Also, please reformat this document following the "style guide" thing in https://github.com/TheCrossroads/discord-guides/blob/master/example/documented and be sure to add a document entry in the `categories.json` file.

Thanks for the contribution! I'll merge as soon as these things are fixed. ☺

**Comment by deansheather** [comment]
~~totally not a bump~~

**Comment by EnigmaticSheep** [comment]
k, tomorrow i'll find time!

**Comment by deansheather** [comment]
*8 days later*

**Comment by deansheather** [comment]
@zounce would you mind copying the raw markdown into another fork and fixing this up yourself? Thanks.

**Comment by zounce** [comment]
👍

**Comment by deansheather** [comment]
Zounce has fixed up this article and this has been merged in #21.

**Pull request closed without merging**
